- client/app/views/calendar_popover_event.coffee
- client/vendor/scripts/bootstrap-timepicker.js
- update and customize bootstrap-timepicker
- fix new start or end time  values may not save on key ENTER
Needs build before merge !
> Fix start and end time messup while editing with arrow keys in popover.

- server/controllers/events.coffee
- server/controllers/tags.coffee
the previous res.error throws an exception.
> Fix error handling on event creation

- client/app/views/menu_item.coffee
- client/app/views/widgets/combobox.coffee
- package.json
> fix(issue 217): validate calendar renaming on input blur

- client/app/locales/fr.coffee
Hello,
Here some changes to improve french translation.
> Improve french strings

- client/app/locales/fr.coffee
GoofyNote : attention, cette application ne fournit pas des calendriers mais des agendas.
> divers typos

- client/app/views/calendar_view.coffee
- client/app/views/styles/_calendar.styl
- client/app/views/templates/list_view_item.jade
* Fix all day events.
* Improve event title readability.
* Add translate for all-day events in list view.
> Some improvements

- client/app/collections/realeventsgenerator.coffee
- client/app/lib/today_checker.coffee
- client/app/models/realevent.coffee
- client/app/models/scheduleitem.coffee
- client/app/views/list_view_item.coffee
- client/app/views/templates/import_event.jade
- client/app/views/templates/list_view_item.jade
- package.json
- server.coffee
- server/models/event.coffee
Commits are self-explanatory, I feel. Let me know if it deserves more explanations.
> Various changes

- client/app/application.coffee
- server/controllers/index.coffee
- server/controllers/routes.coffee
- server/libs/localization_manager.coffee
- server/models/tag.coffee
* fixed a bug resulting in client spamming POST /tags when the page loads
* improved: timezone is now passed directly in the reponse
* Fixed: prevent server crash if an email template is missing. See #330
> Various fixes

- client/app/views/calendar_popover_event.coffee
- client/app/views/calendar_view.coffee
- client/app/views/popover_screens/guests.coffee
- client/app/views/popover_screens/main.coffee
- client/app/views/popover_screens/repeat.coffee
- client/app/views/styles/_popover.styl
- client/app/views/templates/popover_screens/main.jade
- client/app/views/templates/popover_screens/repeat.jade
Based on @clochix feedback, I fixed more stuff.
I feel like commits are self-explanatory, let me know if you want more comments or so.
> Bunch of fixes

- client/app/views/popover_screens/guests.coffee
- server/mails/mail_handler.coffee
* Another fix in the new popover: you could add a new guest with an empty email address, which was wrong
* Raw text version of the invitation emails displayed "false" for when there was no place set.
> Minor fixes

- client/app/assets/img/spinner-white.svg
- client/app/lib/popover_view.coffee
- client/app/views/popover_screens/main.coffee
* Fixed: using white version of the spinner
* Improved (fixed ?): positioning. Please check it out on your computer, since the issue appears with various screen resolution.
> More fixes

- client/event_public_fr.jade
> Typo (issue #352)

- server/libs/localization_manager.coffee
> Fixed: update localization manager when user's locale is updated.

- package.json
- server/mails/mail_handler.coffee
In order to improve invitation behaviour, an organizer should be added in the events sent by email.
> Added: support for ORGANIZER

- server/controllers/events.coffee
I forgot to add the support for ORGANIZER field to ICS download routes.
> Added: ORGANIZER support for ICS download

- client/app/views/popover_screens/main.coffee
It should fix the issue with "crazy times".
> Fixed: automagically adjusted times were not properly set.

- client/app/application.coffee
- client/app/views/calendar_view.coffee
- client/app/views/styles/_base.styl
- client/app/views/styles/_calendar.styl
- client/app/views/styles/_menu.styl
- client/app/views/styles/_responsive.styl
- client/app/views/styles/application.styl
- client/app/views/templates/calendar_header.jade
Responsive was not displaying the list anymore, so I fix it. I changed some weird behaviors with calendar resizing.
I changed the calendar header styles too to make it more compliant with the other apps.
> Fix responsive and header styles

- client/app/collections/scheduleitems.coffee
- client/app/lib/popover_view.coffee
- client/app/locales/en.json
- client/app/locales/fr.json
- client/app/models/scheduleitem.coffee
- client/app/views/calendar_view.coffee
- client/app/views/popover_screens/main.coffee
- client/app/views/popover_screens/repeat.coffee
- client/app/views/styles/_popover.styl
- client/app/views/styles/_responsive.styl
- client/app/views/templates/popover_screens/generic_title.jade
- client/app/views/templates/popover_screens/main.jade
- server/models/user.coffee
See the tickets listed in commit messages
> Fix some bugs

- client/app/router.coffee
- client/app/views/calendar_header.coffee
- client/app/views/calendar_view.coffee
- client/app/views/list_view.coffee
- client/app/views/templates/calendar_header.jade
As discussed with @m4dz and @jsilvestre, the code related to the week view has been removed.
> Remove the week view

- client/app/views/popover_screens/main.coffee
Start time was not behaving as expected.
> Fix issue with start time related to changes made for #465.

- server/mails/mail_handler.coffee
While re-factoring this file to integrate the sharing feature, I removed the part of the code that was responsible for sending mails to the guests.
This pull-request fixes this deletion.
> Fix mail sending

- client/app/views/import_view.coffee
Import was not showing imported events and calendar events anymore. Its probably caused by recent improvements on calendar addition.
Calendar and events were appearing only at refresh, as an event need to get its related calendar's id to determine if it's visible or not. As the newly imported calendar was not fully configured, all events were computed as not visibles.
To fix that, we now save any imported calendar after import, so it got an id and all its events visibility can be computed correctly.
> Fix import issue

- client/app/models/scheduleitem.coffee
> Don't crash when RRULE is invalid

- client/app/helpers.coffee
- client/app/lib/popover_view.coffee
- client/app/locales/en.json
- client/app/router.coffee
- client/app/views/calendar_view.coffee
- client/app/views/event_popover.coffee
- client/app/views/list_view.coffee
- client/app/views/styles/_base.styl
- client/app/views/styles/_responsive.styl
- client/app/views/templates/list_view.jade
> Create an event from EventListView
