cozy/cozy-calendar

- client/app/locales/en.coffee
- client/app/locales/fr.coffee
- client/app/views/menu.coffee
- client/app/views/styles/_menu.styl
- client/app/views/templates/menu.jade
Some css fixes may be nedeed
Added a submenu to "Calendar" menu item. same behaviour as menuitem.
On click, a new calendar is created and "rename" action is triggered so that the user can name it.
Due to codebase system (tag, no calendar without event), a fake event is created on 01/01/1901 for the new calendar to be saved.
> feat(calendar): added to simpler way to add a new calendar. 

- client/app/views/templates/popover_title.jade
Icon is not showing.
It seems a bit too far left.
> fix(icon missing): #223 changed icon name for 'duplicate link'

- client/app/views/styles/_menu.styl
Access options when the calendar name is too long.
> CSS: added break-word to calendar name #299

- package.json
This must be published asap because users depend on it. It's something we (I) forgot in the previous release. See https://forum.cozy.io/t/solved-trouble-accessing-calendar-app/957/5.
Thank you very much.
> Upgraded: cozy-ical

- package.json
- server/mails/mail_handler.coffee
This should fix https://github.com/cozy/cozy-calendar/issues/383.
> Fixed: invitation ICS are marked as request to prevent bugs  when reimported in other clients

- client/app/application.coffee
- client/app/router.coffee
- client/app/views/calendar_header.coffee
- client/app/views/calendar_view.coffee
- client/app/views/styles/_calendar.styl
- client/app/views/styles/_menu.styl
- client/app/views/styles/application.styl
- client/app/views/templates/calendar_header.jade
- client/app/views/templates/menu.jade
I moved settings button to the header because it had a weird behavior when browsing calendar months.
It was the opportunity to fix regressions I added with my previous changes.
> Move settings button to header + fixes

- client/app/collections/scheduleitems.coffee
- client/app/models/scheduleitem.coffee
- client/app/views/menu_item.coffee
* Fix color format to always be in hexadecimal. Refs #435
* Fix recurring event issue with daylight saving. Refs #433
> Fix color format and recurring event issue

- client/app/models/scheduleitem.coffee
When invitation email has been sent, but guests didn't accept or reject the
invitation, changing the event would not trigger an update email.
@aenario could we please merge and publish this commit? Reason is @Benibur asking for it in emergency.
> Fix update email were not sent to guests in one case

- server/mails/mail_handler.coffee
In previous PR, I forgot that the check was also done on the server. This addresses this oversight.
> Fix server-side update email to guests

- client/app/models/scheduleitem.coffee
In the closure's scope, we use "@" to reference parent's scope, without using the fat arrow.
> Fix function scope to use @ in closure

- client/app/views/import_view.coffee
- client/app/views/menu.coffee
A user had problem importing a huge ics file: some event weren't imported.
We import events by batches of 100, but some requests were too heavy and some events were not imported.
I reduced the size of the batches to 50 and everything seems to work now.
> Fix event import

- client/app/views/popover_screens/main.coffee
- client/app/views/styles/_popover.styl
- client/app/views/templates/popover_screens/main.jade
- package.json
As the description input was having the focus, the screen change to the
"full" description screen was not triggered. Because the presence of the input
was the real problem, causing conflict between the native behavior and the
expected behavior, I replaced it by a full block button. I added a span into
this button to avoid overflow issue in Firefox.
*Remark :*
I removed a timeout added by @clochix in commit
5756690ce46952d3d798e6d5d198c4ea4edc09fc related issue #401.
For me there was no reason to add a timeout here, but maybe I am missing a
point.
> Fix the description field focus issue in event popover.

- client/app/application.coffee
- client/app/views/styles/_menu.styl
- client/app/views/styles/_mobile.styl
- client/app/views/styles/application.styl
The problem here was to be able to differenciate a mobile usage from a
"small screen", i.e. responsive, usage.
So a dedicated mobile stylesheet has been added to handle specific style for
mobile, where the Month/List header does not appear anymore.
> Improve UI on mobile.

- client/app/lib/popover_screen_view.coffee
- client/app/lib/popover_view.coffee
- client/app/models/scheduleitem.coffee
- client/app/views/calendar_popover_screen_event.coffee
- client/app/views/popover_screens/alert.coffee
- client/app/views/popover_screens/details.coffee
- client/app/views/popover_screens/guests.coffee
- client/app/views/popover_screens/main.coffee
- client/app/views/popover_screens/repeat.coffee
Related to https://github.com/cozy/cozy-calendar/issues/465
I used two pretty dirty hacks to achieve this fix.
First, I created a local context in the event popover to be able to keep a temporary model between all the popover screens. This model represents the form's state. It's mapped into the original model when the user hits the save button. Using a cleaner solution should have taken too much time and needed more refactor and more regression tests.
Second, I encountered an issue when creating a new event with attendees. The model who was saved to the server was always empty after the "send emails" confirm dialog. I did not find why the app was behaving like this. So I used a dirty temporary variable to store and "freeze" the model's state during the confirm dialog (see …
> Keep the model unchanged until the user hits the save button.

- client/app/application.coffee
- client/app/collections/calendars.coffee
- client/app/collections/scheduleitems.coffee
- client/app/lib/popover_view.coffee
- client/app/models/scheduleitem.coffee
- client/app/views/calendar_popover_event.coffee
- client/app/views/calendar_view.coffee
- client/app/views/menu.coffee
- client/app/views/menu_item.coffee
- client/app/views/popover_screens/details.coffee
- client/app/views/popover_screens/main.coffee
- client/app/views/widgets/combobox.coffee
- server/controllers/index.coffee
- server/controllers/tags.coffee
- server/models/event.coffee
- server/models/tag.coffee
This PR brings a huge change in the way of building the calendar list.
This list is not built anymore with tags set on the timeframe events, but it's
loaded directly server side. We were not able to check all the existing calendar
since all the events were not loaded anymore.
So, this new method implies a lot of changes, like :
* Event filtering (visible or not)
* Calendar update (name/color)
* Calendar deletion
* Sync with event models
* Calendar update in the popover
* Calendar creation in the popover
Also, this PR fixes a regression between two previous fixes : The confirm dialog
when closing the event popover was not shown since the creation of a formModel
property, dedicated to reprensent the form state. The original model was
permanently computed as "unchanged".
> Fix "Add calendar" issue.

- server/models/contact.coffee
I forgot to check for the existence of the field `mediatype` which could make the calendar crash if that is the case. For instance adding an url in the "additionnal informations" subsection could cause this.
> Fix error due to mediatype being undefined

- client/app/models/event.coffee
- client/app/views/popover_screens/main.coffee
- server/controllers/sharings.coffee
At this time the error is just display via an alert message.
We should definetely set up a global error management mechanism for the whole
app.
> Handle sharing error at event creation.

- client/app/views/menu_item.coffee
* Do not change the calendar color when typing
* Only generate calendar color for new calendars (keep the current one when the calendar is renamed)
There is no need to use a proxy form model as in the envent popover, because the model has to be saved when every single change is made (changes are not performed via the same forms).
> Do not change calendar name/color unless anything really changes

- client/app/lib/base_view.coffee
- client/app/lib/popover_view.coffee
- client/app/lib/popup_view.coffee
- client/app/models/event.coffee
- client/app/router.coffee
- client/app/views/calendar_view.coffee
- client/app/views/event_popover.coffee
- client/app/views/pending_event_sharings_button.coffee
- client/app/views/popover_screens/confirm.coffee
- client/app/views/popover_screens/delete.coffee
- client/app/views/popover_screens/main.coffee
action.
* Add a `AddClickOutListener` method in BaseView to handle click outside any
element. This method provides way to ignore given events or source DOM elements.
It used for:
* Recently created Pending shared events button's popup
* Event popover
* Clean the way an event popover is closed. The recent changes on
model/formModel allowed us to remove some code and simplify the whole closing
process
* Enhance the closing method by passing it a callback. This callback is called
only when the event popover has been properly terminated, i.e. when the user
has confirmed that he does not want to keep the change. This new feature is used
* When a new popover pops up
* When the calendar view is changed
* The popover closing detection into CalendarView no rely on event listening,
and not on a …
> Display close warning on every event popover, whatever the source of the close

- client/app/lib/base_view.coffee
- client/app/views/pending_event_sharings_button_item.coffee
- client/app/views/styles/_pending_event_sharings_button.styl
- client/app/views/templates/pending_event_sharings_button_item.jade
Use three states :
* disabled
* busy
* invalid
Each one apply corresponding aria state to elment, the whole UI is done via CSS.
Those three states are set in Base View, so they can now be used by every view
in the app.
> Improve UI for pending shared events notifications.

- client/app/collections/contacts.coffee
- client/app/models/contact.coffee
- client/app/models/event.coffee
- client/app/models/scheduleitem.coffee
- client/app/views/popover_screens/guests.coffee
- client/app/views/styles/_popover.styl
- client/app/views/templates/popover_screens/guest_row.jade
- server/mails/mail_handler.coffee
- server/models/contact.coffee
- server/share/share_handler.coffee
This PR introduces the following changes:
* the search in the guest popover now also proposes Cozy url based on
what is present in the contact application;
* the calendar application can now handle a contact for whom several
Cozy instances are linked;
* if a guest has a Cozy url and an email in his contact information then
the user can decide if she wants to share the invitation or send it by
mail. It is possible to switch between those two possibilities thanks to
two new buttons. The currently selected option has its button
highlighted in blue;
* if it is not possible to switch from email to share, or from share to
email the button corresponding to the unavailable choice is hidden;
* a Cozy url can be typed directly in the search field. If no "@" is
found it is considered as the url of a …
> Enhance guest addition for share

- client/app/application.coffee
- client/app/initialize.coffee
- client/app/models/event.coffee
- client/app/models/sharing.coffee
- client/app/views/popover_screens/main.coffee
As the sharing creation occurs after an event save in the data sytem, we can't
if the sharing succeed or not right after the event creation.
Instead of relying on realtime service (which can fail, be down, etc), we try
to get the shareID every interval of a given time. When the shareID is finally
fetched, we get the sharing to check if its targets contain any error. If so, we
throw them.
If the shareID cannot be fetched, an error is also thrown.
> Check for error in sharing after an event is saved

- client/app/models/scheduleitem.coffee
- server/controllers/events.coffee
- server/share/share_handler.coffee
Based on PR #551 
---
Before this PR the behaviour was to always start the "share routine" on
the server side, even if an event is not shared.
With those changes the "share routine" resembles that of the mail: the
client side of the calendar application adds a parameter `share` to the
url to inform on whether or not the event is shared. The routine is then
launched only when needed.
> Prevent automatic share

- client/app/models/scheduleitem.coffee
- client/app/views/event_popover.coffee
- client/app/views/popover_screens/delete.coffee
- client/app/views/popover_screens/main.coffee
A click on the modal or its "backdrop" element was previously triggering a
"click outside" and a closing of the event popover.
The main problem was that the logic of this modal display was in model,
forbidding access to view properies like `clickOutListener`. So first I fixed
this design by bringing back the modal's logic into the event popover view. It
also simplified the code and removed a dirty hack to keep the model consistent.
Then I added a method to the Modal lib to be able to retrieve the backdrop
element, to then add it to the element list to ignore when they trigger a click
event.
> Fix handling of click in confirm emails modal.

- client/app/views/popover_screens/guests.coffee
- client/app/views/styles/_popover.styl
- client/app/views/templates/popover_screens/guest_row.jade
- client/app/views/templates/popover_screens/guests.jade
As the JS logic behing this screen was based on data recuperation in DOM,
changing the elements broke the feature. So I also adapted the JS code to be now
DOM independant, so future changes in templates should not affect the behaviour
anymore.
> Fix the guests layout in the event popover by using a <table> element.

- client/app/models/realevent.coffee
- client/app/models/scheduleitem.coffee
Multiple-days events are now displayed with their starting and ending time respectively in the first and last day
> Fix multiple days event displayed as "All day" in list view

- server/share/share_handler.coffee
On older version of node the method `find` for the array does not exist
which causes problems. With this commit the method is defined in all
cases.
This corresponds to the bug: #572
> Fix "legacy" issue with method `find`

- client/app/collections/calendars.coffee
- client/app/models/calendar.coffee
As we are going to use a model object for calendar instead of refering it as a
Tag, this issue was the good opportunity to finally create a Calendar class.
At this time, it only inherit from Tag and ad an empty color detection.
It allows to avoid some be UI issues when a calendar color is not set.
This change implies some little updates in CalendarColleciton class.
> Fix calendar without color

- client/app/lib/popover_view.coffee
This PR add a check for event popover's vertical position. The popover was
previously out of viewport in a given conditions.
The idea with this PR is to center it vertically when it overflows the viewport.
> Fix event popover position

- client/app/application.coffee
- client/app/views/calendar_view.coffee
- server/controllers/events.coffee
- server/controllers/index.coffee
- test/event_model_test.coffee
Two methods were generating warnings and I got tired of it so here are
the modifications… ;-)
There are also fat arrows that are replaced by simple ones, as syntastic
was complaining.
> Remove depreciation warning for moment library

- client/app/lib/request.coffee
- client/app/models/event.coffee
- server/controllers/routes.coffee
- server/helpers/client.coffee
- server/helpers/utils.coffee
Before this commit when we wanted to get the sharing document associated
with a shared event we attempted a fetch of the document which id
matches the "shareID". The problem was that if we are the recipient of
the shared event no document with this id exists hence resulting in the
data-system returning an error and the client browser displaying a 404
in the console.
To avoid this behavior a new route was created on the server side of the
application to call the route "data/exist/:id" of the data-system.
Having that we now start by asking if a document with that id exists and
if that is the case we fetch it and if not we fetch the appropriate
sharing document. We no longer produce errors.
> No lookup error in DS for unexisting sharing

- server/controllers/ical.coffee
Fix #317.
When the calendar app is installed for the first time a dummy event with the exact date 1901-01-01 is created. When a new calendar is created, each time, a dummy event with the date 1901-01-01 RELATED TO THE LOCAL TIMEZONE is created (so 1901-01-01 more or less 12h).
There is no way to tell the difference between the dummy event and another event from the DB, so this fix doesn't export any events for end dates before the year 1901 included.
I choose to detect only the year instead of be more accurate (we could prevent only events of 1901-01-01 and 1900-12-31) to not slow down the performance when exporting a lot of events, while using momentJS to keep date formats compatibility.
> Fix bug about dummy event when exporting calendar

- client/app/lib/socket_listener.coffee
> Avoid error when docType is undefined in SocketListener.handleModel

- client/app/views/settings_modal.coffee
Fix #549
I did not test with a real webDav account but I mocked one in the IndexController and I have been able to reproduce the issue, and then to test my fix.
> Handle account.token legacy for webDav accounts
